### ISSUE TITLE
Add samples for configuration in kubernetes with opentelemetry-collector / opentelemetry-operator

### ISSUE THREAD

**Issue by davidB** [davidB/axum-tracing-opentelemetry#37]
eg:
```yaml
        # to inject environment variables only by opentelemetry-operator
        instrumentation.opentelemetry.io/inject-sdk: "monitoring/instrumentation"
        instrumentation.opentelemetry.io/container-names: "user-container"
    spec:
      containers:
        - name: user-container
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: '{{ .Release.Name }}'
          env:
            # this env variable is not injected by instrumentation.opentelemetry.io/inject-sdk
            # - name: OTEL_EXPORTER_OTLP_PROTOCOL
            #   value: 'grpc'
            # override to not use the name of knative deployement (with version)
            - name: OTEL_SERVICE_NAME
              value: '{{ .Release.Name }}'
    ```
