### ISSUE TITLE
suggestion define `examples` as a workspace

### ISSUE THREAD

**Issue by davidB** [davidB/axum-tracing-opentelemetry#42]
`examples/Cargo.toml`

```toml
[workspace]
members = ["*"]
exclude = ["target"]
resolver = "2"
```
